### ISSUE TITLE
No se muestran las materias añadidas

### ISSUE THREAD

**Issue by juli-rivero** [FdelMazo/FIUBA-Repos#18]
Creo que el problema está aca:

#### src/components/MainApp.js

    const materias = React.useMemo(() => {
    const codigosMaterias = [
      ...new Set(
        data.flatMap((r) => r.topics.filter((t) => t.match(/^\d\d\d\d$/))),
      ),
    ];

Donde se filtran los códigos que tienen 4 digitos, mientras que los nuevos codigos son de letras y numeros. Ejemplo: "TB022"

**Comment by FdelMazo** [comment]
Genial, me habia olvidado de esa regex. Habría que modificar ese chequeo por solamente fijarse si el topic esta presente en el JSON de materias

**Comment by juli-rivero** [comment]
Dale! Durante la semana hago ese retoque pequeño y subo el pr ;D
