### ISSUE TITLE
No se muestran materias con 0 repos

### ISSUE THREAD

**Issue by juli-rivero** [FdelMazo/FIUBA-Repos#19]
La linea que lo impide es la linea 57 de MainApp.js: `return allMaterias.filter((m) => m.reponames?.size > 0);`

Esto por un lado esta bueno, ya que no molestan, pero por otro me impide ver el código de la materia para agregar el topic en mis repositorios (tengo que venir aca a src/data/materias.json y ver el código de la materia que quiero agregar, en caso que esté)

Sugiero que se piense una manera de agregar estos nombres y codigos desde la página. Por ejemplo con un checkbox o estando deshabilitados.

**Comment by FdelMazo** [comment]
Tal vez agregar las materias solo en la busqueda? Si no tengo nada buscado, aparecen las materias con al menos un repo, pero si estoy buscando especificamente una materia y quiero saber el código, me aparece ahí vacía

**Comment by juli-rivero** [comment]
Me gusta esa idea! Para el finde que viene estará hecho y hago el pr
