### ISSUE TITLE
Integracion con google drive

### ISSUE THREAD

**Issue by n-zu** [FdelMazo/FIUBA-Repos#6]
Hay varias materias para las cuales no tengo un repo pero si una carpeta de drive

Estaria bueno poder integrarlo de algun modo

[Link Drive](https://drive.google.com/drive/folders/1fCWCFjvA8NwUsgo2lksKE4UP89N1iSey?usp=sharing)

**Comment by FdelMazo** [comment]
No estoy seguro de si eso es algo que le vendría bien a la página. Lo que quiero lograr con este sitio es recolectar material de fiuba de manera automática, para evitar que a mano haya un moderador que va aceptando/rechazando links/pdfs/parciales, como se hace en todas las otras wikis de la fiuba.

(es verdad... esto no es 100% automático porque aún así le pedís a la gente que cambie los topics de sus repos, pero me sigue pareciendo de muy baja fricción esa acción, y no requiere de moderación)

Si se te ocurre alguna forma de que agreguemos links de drive sin hardcodearlos, lo pensamos juntos!

**Comment by n-zu** [comment]
Genial, claro, seria imposible sin aumentar el trabajo manual.

Tal vez una forma podria ser poniendo el link y una desc como un issue/discussion 🤔

**Comment by FdelMazo** [comment]
No me convence mucho :(

Creo que prefiero que esta pagina fomente a la gente a subir código a github, en vez de dar vueltas por google (que tiene mil lios de permisos, no es cómodo para entender el historial, etc)

**Comment by NicolasEzequielZulaicaRivera** [comment]
> fomente a la gente a subir código a github

**Comment by n-zu** [comment]
>  fomente a la gente a subir código a github

La verdad que si, mejor estandarizarlo
